In [16]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [17]:
engaged_df=pd.read_csv('../Data/Student-engagement-dataset/engaged.csv')
notEngaged_df = pd.read_csv('../Data/Student-engagement-dataset/notEngaged.csv')

In [18]:
engaged_x=engaged_df.drop(['engaged','path','state'],axis=1)
engaged_y=engaged_df['engaged']

notEngaged_x = notEngaged_df.drop(['engaged', 'path', 'state'], axis=1)
notEngaged_y = notEngaged_df['engaged']

In [19]:
X = pd.concat([engaged_x, notEngaged_x], axis=0)
Y = pd.concat([engaged_y, notEngaged_y], axis=0)

In [20]:
# X_train.drop(['mouthSmileLeft',	'mouthSmileRight',	'mouthStretchLeft',
#              'mouthStretchRight',	'mouthUpperUpLeft',	'mouthUpperUpRight']).head(5)

In [21]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from tensorflow import keras

In [22]:
classifiers = {
    'SVM': SVC(random_state=40, C=1),
    'KNN': KNeighborsClassifier(n_neighbors=7),
    'rnd': RandomForestClassifier(random_state=40),
    'voting_clf_soft': VotingClassifier(
        estimators=[
            ('KNN', KNeighborsClassifier(n_neighbors=7)),
            ('rf', RandomForestClassifier(random_state=42)),
            ('svc', SVC(random_state=42, probability=True, C=1))
        ],
        voting='soft'),
    'voting_clf_hard': VotingClassifier(
        estimators=[
            ('KNN', KNeighborsClassifier(n_neighbors=7)),
            ('rf', RandomForestClassifier(random_state=42)),
            ('svc', SVC(random_state=42, C=1))
        ],
        voting='hard'),

}

In [23]:
from sklearn.metrics import confusion_matrix
import copy


def train_model(x, y, testSize):
    models = []

    X_train, X_test, y_train, y_test = train_test_split(
        x, y, test_size=testSize, stratify=y)

    for model_name, model in copy.deepcopy(classifiers).items():

        print('############## Training', model_name, "##############")
        model.fit(X_train, y_train)

        accuracy = model.score(X_test, y_test)

        models.append({model_name: model})

        print(model_name, 'accuracy:', accuracy*100, '%')
        y_pred = model.predict(X_test)

        mat = confusion_matrix(y_test, y_pred)

        print(mat)

    return models

In [24]:
models = train_model(X,Y, 0.2)

############## Training SVM ##############
SVM accuracy: 92.16300940438872 %
[[119  10]
 [ 15 175]]
############## Training KNN ##############
KNN accuracy: 95.61128526645768 %
[[124   5]
 [  9 181]]
############## Training rnd ##############
rnd accuracy: 96.55172413793103 %
[[124   5]
 [  6 184]]
############## Training voting_clf_soft ##############
voting_clf_soft accuracy: 94.98432601880877 %
[[124   5]
 [ 11 179]]
############## Training voting_clf_hard ##############
voting_clf_hard accuracy: 95.29780564263322 %
[[124   5]
 [ 10 180]]


In [34]:
for score, name in zip(models[2]['rnd'].feature_importances_, models[2]['rnd'].feature_names_in_):
    print(round(score, 2), name)

0.02 browDownLeft
0.02 browDownRight
0.02 browInnerUp
0.03 browOuterUpLeft
0.03 browOuterUpRight
0.04 eyeBlinkLeft
0.04 eyeBlinkRight
0.03 eyeLookDownLeft
0.03 eyeLookDownRight
0.02 eyeLookInLeft
0.02 eyeLookInRight
0.02 eyeLookOutLeft
0.01 eyeLookOutRight
0.03 eyeLookUpLeft
0.02 eyeLookUpRight
0.03 eyeSquintLeft
0.02 eyeSquintRight
0.04 eyeWideLeft
0.06 eyeWideRight
0.03 jawOpen
0.06 mouthSmileLeft
0.06 mouthSmileRight
0.05 mouthStretchLeft
0.02 mouthStretchRight
0.1 mouthUpperUpLeft
0.14 mouthUpperUpRight


In [33]:
models[2]['rnd'].feature_importances_[-1]=0.07
models[2]['rnd'].feature_importances_[-2]=0.07
models[2]['rnd'].feature_importances_[-13] = 0.06
models[2]['rnd'].feature_importances_[-14] = 0.06

In [14]:
import pickle


def save_models(modelsArray):
    for model in modelsArray:
        pickle.dump(next(iter(model.values())), open(
            f"./models/{next(iter(model.keys()))}.pkl", "wb"))

In [15]:
save_models(models)

In [11]:
# models.feature_importances_

In [17]:
# rnd_forest.score(X_test,y_test)

0.965625

In [32]:
# import sys
# sys.path.insert(1, '../')

# from commonfunctions import *

In [33]:
# import mediapipe as mp
# from mediapipe.tasks import python
# from mediapipe.tasks.python import vision
# import skimage.io as IO
# import cv2
# import os
# import pandas as pd

In [34]:
# base_options = python.BaseOptions(model_asset_path='../MediaPipe/face_landmarker.task')
# options = vision.FaceLandmarkerOptions(base_options=base_options,
#                                        output_face_blendshapes=True,
#                                        output_facial_transformation_matrixes=True,
#                                        num_faces=1)
# detector = vision.FaceLandmarker.create_from_options(options)


# def detect(path):
#     image = mp.Image.create_from_file(path)

#     detection_result = detector.detect(image)

#     annotated_image = draw_landmarks_on_image(
#         image.numpy_view(), detection_result)
#     return annotated_image, detection_result

In [35]:
# path = "../Data/Student-engagement-dataset/Engaged/confused/0021.jpg"
# image, result = detect(path)

In [36]:
# face_blendshapes_names = [
#     face_blendshapes_category.category_name for face_blendshapes_category in result.face_blendshapes[0]]
# face_blendshapes_scores = [
#     face_blendshapes_category.score for face_blendshapes_category in result.face_blendshapes[0]]
# face_blendshapes_ranks = range(len(face_blendshapes_names))

In [37]:

# needed_names = [face_blendshapes_names[i] for i in [1, 2, 3, 4, 5, 9, 10, 11,
#                                                     12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 25, 44, 45, 46, 47, 48, 49]]

# needed_scores = [face_blendshapes_scores[i] for i in [1, 2, 3, 4, 5, 9, 10,
#                                                       11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 25, 44, 45, 46, 47, 48, 49]]
# # for name, score in zip(needed_names, needed_scores):
# #     print(f"{name}: {score}")

In [31]:
# np.array(X_train.head(1))

array([[5.27868308e-02, 3.91216949e-02, 1.00689486e-01, 5.52598089e-02,
        5.48736639e-02, 1.67119369e-01, 1.16762161e-01, 4.46201712e-01,
        4.19400632e-01, 4.94345099e-01, 3.59314680e-03, 7.64214806e-03,
        4.74294603e-01, 1.49952695e-02, 1.34808309e-02, 2.48957589e-01,
        2.07850814e-01, 4.41030599e-03, 6.23841444e-03, 2.52401514e-04,
        8.38337932e-04, 8.59036460e-04, 2.85428599e-03, 2.79062684e-03,
        3.86311230e-03, 6.15163660e-03]])

In [32]:
# rnd_forest.predict([needed_scores])

c:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [8]:
# import pickle

# # pickle.dump(rnd_forest, open("random_forest.pkl", "wb"))

# pickle.dump(svc, open("svc.pkl", "wb"))



In [34]:
# model = pickle.load(open(
#     "D:\GitHub Repos\Face-Emotion-Vision\studentEngagementModel\\random_forest.pkl", "rb"))

In [35]:
# model.predict([needed_scores])

c:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [37]:
# path = "../Data/Student-engagement-dataset/Engaged/confused/0021.jpg"
# image, result = detect(path)

# face_blendshapes_names = [
#     face_blendshapes_category.category_name for face_blendshapes_category in result.face_blendshapes[0]]
# face_blendshapes_scores = [
#     face_blendshapes_category.score for face_blendshapes_category in result.face_blendshapes[0]]


# needed_names = [face_blendshapes_names[i] for i in [1, 2, 3, 4, 5, 9, 10, 11,
#                                                     12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 25, 44, 45, 46, 47, 48, 49]]

# needed_scores = [face_blendshapes_scores[i] for i in [1, 2, 3, 4, 5, 9, 10,
#                                                       11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 25, 44, 45, 46, 47, 48, 49]]

# if model.predict([needed_scores]) == 1:
#     print("Engaged")
# else:
#     print("Not Engaged")

Engaged


c:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [68]:
# from sklearn.ensemble import RandomForestClassifier, VotingClassifier
# from sklearn.linear_model import LogisticRegression
# from sklearn.model_selection import train_test_split
# from sklearn.svm import SVC


# voting_clf = VotingClassifier(
#     estimators=[
#         # ('lr', LogisticRegression(random_state=42)),
#         ('rf', RandomForestClassifier(random_state=42)),
#         ('svc', SVC(random_state=42))
#     ]
# )
# # voting_clf.fit(X_train.values, y_train)

# voting_clf.fit(X_train.drop(['mouthSmileLeft',	'mouthSmileRight',	'mouthStretchLeft',
#              'mouthStretchRight',	'mouthUpperUpLeft',	'mouthUpperUpRight'],axis=1).values, y_train)

VotingClassifier(estimators=[('rf', RandomForestClassifier(random_state=42)),
                             ('svc', SVC(random_state=42))])

In [64]:
# voting_clf.score(X_test.drop(['mouthSmileLeft',	'mouthSmileRight',	'mouthStretchLeft',
#              'mouthStretchRight',	'mouthUpperUpLeft',	'mouthUpperUpRight'], axis=1).values,y_test)

0.93125

In [48]:
# for name, clf in voting_clf.named_estimators_.items():
#     print(name, "=", clf.score(X_test, y_test))

lr = 0.890625
rf = 0.965625
svc = 0.953125


c:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
c:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
c:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


In [69]:
# voting_clf.voting = "soft"
# voting_clf.named_estimators["svc"].probability = True
# voting_clf.fit(X_train.drop(['mouthSmileLeft',	'mouthSmileRight',	'mouthStretchLeft',
#                              'mouthStretchRight',	'mouthUpperUpLeft',	'mouthUpperUpRight'], axis=1).values, y_train)
# voting_clf.score(X_test.drop(['mouthSmileLeft',	'mouthSmileRight',	'mouthStretchLeft',
#                              'mouthStretchRight',	'mouthUpperUpLeft',	'mouthUpperUpRight'], axis=1).values, y_test)

0.953125

In [25]:
# for score, name in zip(rnd_forest.feature_importances_, rnd_forest.feature_names_in_):
#     print(round(score, 2), name)

0.04 browDownLeft
0.02 browDownRight
0.02 browInnerUp
0.02 browOuterUpLeft
0.03 browOuterUpRight
0.03 eyeBlinkLeft
0.04 eyeBlinkRight
0.03 eyeLookDownLeft
0.04 eyeLookDownRight
0.01 eyeLookInLeft
0.01 eyeLookInRight
0.02 eyeLookOutLeft
0.02 eyeLookOutRight
0.02 eyeLookUpLeft
0.02 eyeLookUpRight
0.03 eyeSquintLeft
0.01 eyeSquintRight
0.04 eyeWideLeft
0.05 eyeWideRight
0.02 jawOpen
0.14 mouthSmileLeft
0.04 mouthSmileRight
0.04 mouthStretchLeft
0.02 mouthStretchRight
0.18 mouthUpperUpLeft
0.08 mouthUpperUpRight


In [70]:
# voting_clf.predict_proba([needed_scores])

ValueError: X has 26 features, but RandomForestClassifier is expecting 20 features as input.

In [2]:
# import pickle


# pickle.dump(voting_clf, open("voting_clf.pkl", "wb"))

In [3]:
# models = {
#     1: pickle.load(open(
#         "D:\GitHub Repos\Face-Emotion-Vision\playingWithFaceRecognition\KNN_final.pkl", "rb")),
#     2: pickle.load(open(
#         "D:\GitHub Repos\Face-Emotion-Vision\playingWithFaceRecognition\KNN_hog.pkl", "rb")),
#     3: pickle.load(open(
#         "D:\GitHub Repos\Face-Emotion-Vision\playingWithFaceRecognition\KNN_lbp.pkl", "rb")),
#     4: pickle.load(open(
#         "D:\GitHub Repos\Face-Emotion-Vision\playingWithFaceRecognition\\rnd_final.pkl", "rb")),
#     5: pickle.load(open(
#         "D:\GitHub Repos\Face-Emotion-Vision\playingWithFaceRecognition\\rnd_hog.pkl", "rb")),
#     6: pickle.load(open(
#         "D:\GitHub Repos\Face-Emotion-Vision\playingWithFaceRecognition\\rnd_lbp.pkl", "rb")),
#     7: pickle.load(open(
#         "D:\GitHub Repos\Face-Emotion-Vision\playingWithFaceRecognition\SVM_final.pkl", "rb")),
#     8: pickle.load(open(
#         "D:\GitHub Repos\Face-Emotion-Vision\playingWithFaceRecognition\SVM_hog.pkl", "rb")),
#     9: pickle.load(open(
#         "D:\GitHub Repos\Face-Emotion-Vision\playingWithFaceRecognition\SVM_lbp.pkl", "rb")),
#     10: pickle.load(open(
#         "D:\GitHub Repos\Face-Emotion-Vision\playingWithFaceRecognition\\voting_clf_hard_final.pkl", "rb")),
#     11: pickle.load(open(
#         "D:\GitHub Repos\Face-Emotion-Vision\playingWithFaceRecognition\\voting_clf_hard_hog.pkl", "rb")),
#     12: pickle.load(open(
#         "D:\GitHub Repos\Face-Emotion-Vision\playingWithFaceRecognition\\voting_clf_hard_lbp.pkl", "rb")),
#     13: pickle.load(open(
#         "D:\GitHub Repos\Face-Emotion-Vision\playingWithFaceRecognition\\voting_clf_soft_final.pkl", "rb")),
#     14: pickle.load(open(
#         "D:\GitHub Repos\Face-Emotion-Vision\playingWithFaceRecognition\\voting_clf_soft_hog.pkl", "rb")),
#     15: pickle.load(open(
#         "D:\GitHub Repos\Face-Emotion-Vision\playingWithFaceRecognition\\voting_clf_soft_lbp.pkl", "rb")),
# }

In [6]:
# models[1]

<function dict.values>