In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
engaged_df=pd.read_csv('../Data/Student-engagement-dataset/engaged.csv')
notEngaged_df = pd.read_csv('../Data/Student-engagement-dataset/notEngaged.csv')

In [4]:
engaged_x=engaged_df.drop(['engaged','path','state'],axis=1)
engaged_y=engaged_df['engaged']

notEngaged_x = notEngaged_df.drop(['engaged', 'path', 'state'], axis=1)
notEngaged_y = notEngaged_df['engaged']

In [8]:
engaged_X_train, engaged_X_test, engaged_y_train, engaged_y_test = train_test_split(
    engaged_x, engaged_y, train_size=0.8, random_state=42)

notEngaged_X_train, notEngaged_X_test, notEngaged_y_train, notEngaged_y_test = train_test_split(
    notEngaged_x, notEngaged_y, train_size=0.8, random_state=42)

In [11]:
X_train=pd.concat([engaged_X_train,notEngaged_X_train],axis=0)
X_test = pd.concat([engaged_X_test, notEngaged_X_test], axis=0)
y_train = pd.concat([engaged_y_train, notEngaged_y_train], axis=0)
y_test = pd.concat([engaged_y_test, notEngaged_y_test], axis=0)

In [12]:
## just testing

from sklearn.ensemble import RandomForestClassifier

rnd_forest=RandomForestClassifier()

rnd_forest.fit(X_train,y_train)

RandomForestClassifier()

In [17]:
rnd_forest.score(X_test,y_test)

0.965625

In [18]:
from sklearn.svm import SVC

svc=SVC()

svc.fit(X_train,y_train)

SVC()

In [19]:
svc.score(X_test,y_test)

0.953125

In [20]:
import sys
sys.path.insert(1, '../')

from commonfunctions import *

In [21]:
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
import skimage.io as IO
import cv2
import os
import pandas as pd

In [23]:
base_options = python.BaseOptions(model_asset_path='../MediaPipe/face_landmarker.task')
options = vision.FaceLandmarkerOptions(base_options=base_options,
                                       output_face_blendshapes=True,
                                       output_facial_transformation_matrixes=True,
                                       num_faces=1)
detector = vision.FaceLandmarker.create_from_options(options)


def detect(path):
    image = mp.Image.create_from_file(path)

    detection_result = detector.detect(image)

    annotated_image = draw_landmarks_on_image(
        image.numpy_view(), detection_result)
    return annotated_image, detection_result

In [25]:
path = "../Data/Student-engagement-dataset/Engaged/confused/0021.jpg"
image, result = detect(path)

In [26]:
face_blendshapes_names = [
    face_blendshapes_category.category_name for face_blendshapes_category in result.face_blendshapes[0]]
face_blendshapes_scores = [
    face_blendshapes_category.score for face_blendshapes_category in result.face_blendshapes[0]]
face_blendshapes_ranks = range(len(face_blendshapes_names))

In [27]:

needed_names = [face_blendshapes_names[i] for i in [1, 2, 3, 4, 5, 9, 10, 11,
                                                    12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 25, 44, 45, 46, 47, 48, 49]]

needed_scores = [face_blendshapes_scores[i] for i in [1, 2, 3, 4, 5, 9, 10,
                                                      11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 25, 44, 45, 46, 47, 48, 49]]
# for name, score in zip(needed_names, needed_scores):
#     print(f"{name}: {score}")

In [31]:
np.array(X_train.head(1))

array([[5.27868308e-02, 3.91216949e-02, 1.00689486e-01, 5.52598089e-02,
        5.48736639e-02, 1.67119369e-01, 1.16762161e-01, 4.46201712e-01,
        4.19400632e-01, 4.94345099e-01, 3.59314680e-03, 7.64214806e-03,
        4.74294603e-01, 1.49952695e-02, 1.34808309e-02, 2.48957589e-01,
        2.07850814e-01, 4.41030599e-03, 6.23841444e-03, 2.52401514e-04,
        8.38337932e-04, 8.59036460e-04, 2.85428599e-03, 2.79062684e-03,
        3.86311230e-03, 6.15163660e-03]])

In [32]:
rnd_forest.predict([needed_scores])

c:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [33]:
import pickle

pickle.dump(rnd_forest, open("random_forest.pkl", "wb"))

pickle.dump(svc, open("svc.pkl", "wb"))



In [34]:
model = pickle.load(open(
    "D:\GitHub Repos\Face-Emotion-Vision\studentEngagementModel\\random_forest.pkl", "rb"))

In [35]:
model.predict([needed_scores])

c:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [37]:
path = "../Data/Student-engagement-dataset/Engaged/confused/0021.jpg"
image, result = detect(path)

face_blendshapes_names = [
    face_blendshapes_category.category_name for face_blendshapes_category in result.face_blendshapes[0]]
face_blendshapes_scores = [
    face_blendshapes_category.score for face_blendshapes_category in result.face_blendshapes[0]]


needed_names = [face_blendshapes_names[i] for i in [1, 2, 3, 4, 5, 9, 10, 11,
                                                    12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 25, 44, 45, 46, 47, 48, 49]]

needed_scores = [face_blendshapes_scores[i] for i in [1, 2, 3, 4, 5, 9, 10,
                                                      11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 25, 44, 45, 46, 47, 48, 49]]

if model.predict([needed_scores]) == 1:
    print("Engaged")
else:
    print("Not Engaged")

Engaged


c:\Users\lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
