In [1]:
import numpy as np
m = [[1,2,4],
     [2,2,3],
     [1,4,5]]
def ComputeLBP(x,y,arr):
    f=s=-1
    value=0
    height,width= arr.shape
    for i in range(8):
        if(i==3 or i==7):
            f=0
        elif(i>3):
            f=1
        if(i==1 or i==5):
            s=0
        elif(i>1 and i<5):
            s=1
        else: 
            s=-1
        if(x+f>-1 and x+f<height and y+s>-1 and y+s<width):
                value+=pow(2,7-i) if arr[x+f,y+s]>arr[x,y] else 0
    return value

def LBP (arr):
    tempArr=np.copy(arr)
    hight,width= tempArr.shape
    for i in range(hight):
        for j in range(width):
            tempArr[i,j] = ComputeLBP(i,j,tempArr)
    return tempArr        
print(LBP(m))

[[ 28  25   1]
 [104 221 135]
 [112 241 193]]
